# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "HACK THE SYSTEM_"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  A Bootstrap 4 start up project for Jekyll and Github Pages
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "gnunicorn/hack-the-system"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - /docs
  - /ueber
  - /impressum

docs: 
  - title: Modernes Arbeiten
    pages:
      - title: Online Plenar
        url: /docs/arbeiten/online-plenar
        pages:
          - title: Tools übersicht
            url: /docs/arbeiten/online-plenar/tools
          - title: Moderation
            url: /docs/arbeiten/online-plenar/moderation
          - title: Zoom Tips & Tricks
            url: /docs/arbeiten/online-plenar/zoom
      - title: Gemeinsam Arbeiten
        url: /docs/arbeiten/gemeinsam
        pages:
          - title: Dokemente erarbeiten
            url: /docs/arbeiten/dokumente
  - title: Wählerinnenvereinigung / Partei
    url: /docs/vereinigung/
    pages:
      - title: Gründung
        url: /docs/vereinigung/gründung
        pages:
          - title: Vorraussetzungen
            url: /docs/vereinigung/gründung/vorraussetzungen
          - title: Formalien
            url: /docs/vereinigung/gründung/formalia
          - title: Ablauf
            url: /docs/vereinigung/gründung/vorraussetzungen

      - title: An Wahlen teilnehmen
        url: /docs/vereinigung/wahlen
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
